version: "3"

services:
  acme_nexus:
    image: sonatype/nexus3
    container_name: acme_nexus
    hostname: nexus
    domainname: acme.com
    volumes:
      - acme_nexus:/nexus-data
    networks:
      - acme

volumes:
  acme_nexus:
    external:
      name: acme_nexus

networks:
  acme:
    external:
      name: acme
