version: "3"

services:
  acme_nexus:
    image: sonatype/nexus3
    container_name: acme_nexus
    restart: always
    hostname: nexus
    domainname: acme.com
    user: root
    ports:
      - 8002:80 # Debug
    volumes:
      - acme_nexus:/nexus-data
      - ./resources/nexus-default.properties:/opt/sonatype/nexus/etc/nexus-default.properties
    networks:
      acme:
        aliases:
          - nexus.acme.com

volumes:
  acme_nexus:
    external:
      name: acme_nexus

networks:
  acme:
    external:
      name: acme
