version: "3"

services:
  acme_docker_ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: acme_docker_ui
    restart: always
    hostname: docker-ui
    domainname: acme.com
    ports:
      - 8003:80 # Debug
    environment:
      - ENV_DOCKER_REGISTRY_HOST=acme_docker_registry
      - ENV_DOCKER_REGISTRY_PORT=80
    depends_on:
      - acme_docker_registry
    networks:
      acme:
        aliases:
          - docker-ui.acme.com

  acme_docker_registry:
    image: registry:2
    container_name: acme_docker_registry
    restart: always
    hostname: docker
    domainname: acme.com
    ports:
      - 8004:80 # Debug
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:80
    volumes:
      - acme_docker_registry:/var/lib/registry
    networks:
      acme:
        aliases:
          - docker.acme.com
          - docker-registry.acme.com

volumes:
  acme_docker_registry:
    external:
      name: acme_docker_registry

networks:
  acme:
    external:
      name: acme
