version: "3"

services:
  acme_haproxy:
    image: haproxy
    container_name: acme_haproxy
    restart: always
    hostname: haproxy
    domainname: acme.com
    ports:
      - 80:80
      - 8000:1936 # Debug
    volumes:
      - ./resources/etc/haproxy:/usr/local/etc/haproxy
    networks:
      acme:
        aliases:
          - haproxy.acme.com

networks:
  acme:
    external:
      name: acme
