version: "3"

services:
  acme_jenkins:
    image: acmebank/jenkins
    container_name: acme_jenkins
    restart: always
    hostname: jenkins
    domainname: acme.com
    ports:
      - 8001:8080 # Debug
    volumes:
      - acme_jenkins:/var/jenkins_home
      - ./resources/settings.xml:/opt/maven/default/conf/settings.xml
    networks:
      acme:
        aliases:
          - jenkins.acme.com

volumes:
  acme_jenkins:
    external:
      name: acme_jenkins

networks:
  acme:
    external:
      name: acme
